version: "2"
services:
  saving-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    volumes:
      - .:/usr/src/app/saving

networks: 
  default: 
    external: 
      name: data-network 

    # depends_on:
    #   - auth-service
    #   - database-saving
  # database-saving:
  #   # Official Postgres image from DockerHub (we use the last version)
  #   image: 'postgres:latest'
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_USER: admin # The PostgreSQL user (useful to connect to the database)
  #     POSTGRES_PASSWORD: 123 # The PostgreSQL password (useful to connect to the database)
  #     POSTGRES_DB: saving_database # The PostgreSQL default database (automatically created at first launch)
    
  #   volumes:
  #     - ./db-data/:/var/lib/postgresql/data/
